name: Continuos Integration Jorge Panzera

on:
  push:
    branches:
      - master

jobs:
  build:
    name: SAST Credentials y Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Pruebas de SAST
        run: echo "Ejecucion de pruebas de SAST"

      - name: Armar archivo de credenciales
        env:
          USERNAME: '${{ secrets.USERNAME }}'¨
          PASSWORD: '${{ secrets.PASSWORD}}'
        run: envsubst < credentials.ini.tpl > credentials.ini

      - name: Mostrar credentials.ini
        run: |
          cat credentials.ini  

      - name: Build Docker Image
        run: |
          docker build -t devops_ws . --tag devops_ws_$(date +%s)
