name: Validar Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  validate:
    name: Practica 3 Ejercicio 3
    runs-on: ubuntu-latest

    env:
      ALLOW_PULL_REQUEST: false

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Verificar si existe archivo allow_pull_request.txt
        id: check_file
        run: |
          if [ -f "allow_pull_request.txt" ]; then
            echo "File 'allow_pull_request.txt' found."
            echo "ALLOW_PULL_REQUEST=true" >> $GITHUB_ENV
          else
            echo "File 'allow_pull_request.txt' not found."
          fi

      - name: Mensaje Condicional para Pull Request
        run: |
          if [[ "$ALLOW_PULL_REQUEST" == "true" ]]; then
            echo "Permitiendo Pull Request"
          else
            echo "Build fallida. Impidiendo Pull Request"
            exit 1
          fi
